### ISSUE TITLE
API to query secrets by name?

### ISSUE THREAD

**Issue by 200sc** [DelineaXPM/tss-sdk-go#5]
The browser interface appears to make a call like this:

`
https://<tenant>.secretservercloud.com/api/v1/secrets?paging.filter.includeRestricted=true&paging.filter.searchText=<text>&paging.filter.extendedFields=Machine&paging.filter.extendedFields=Notes&paging.filter.extendedFields=Username&paging.filter.doNotCalculateTotal=true&paging.sortBy[0].name=Name&paging.sortBy[0].direction=Asc&paging.take=30&&paging.skip=0
`

When filling in this field: 
![image](https://user-images.githubusercontent.com/4564184/186946120-7b802750-3d8e-42e4-b97a-9bc6ccc98ce5.png)

And this returns apparently parsable json. 

Is this API stable? If it is, can the SDK be extended to support querying by secret name?

**Comment by tylerezimmerman** [comment]
@200sc We are looking into this. Technically, we are treating this as a feature request rather than a bug.

**Comment by delineaKrehl** [comment]
@200sc You can see there is now a PR to fulfill your request. Instead of creating a single Query By Name interface, I implemented two more generic ones.

1. An API endpoint to do the full text search as you provided in your screen shot.
2. An API endpoint to do an exact search on a given field

If you want to search for an exact name you can use the second endpoint mentioned
